import type { MinionDef, MinionInst, Keyword } from "./types";
import { uid } from "./rng";

export const TRIBE_LABEL: Record<MinionDef["tribe"], string> = {
  beast: "野兽",
  murloc: "鱼人",
  mech: "机械",
  demon: "恶魔",
  dragon: "龙",
  pirate: "海盗",
  neutral: "中立",
};

export const KEYWORD_LABEL: Record<Keyword, string> = {
  taunt: "嘲讽",
  divineShield: "圣盾",
  windfury: "风怒",
  poisonous: "剧毒",
  reborn: "复生",
  cleave: "顺劈",
};

export const MINIONS: MinionDef[] = [
  // —— 1 级 ——
  {
    id: "alleycat",
    name: "巷道猫",
    art: "CFM_315",
    tier: 1,
    tribe: "beast",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [{ kind: "battlecry_summon", tokenId: "tabbycat" }],
    text: "战吼：召唤一只 1/1 的虎斑猫。",
  },
  {
    id: "rockpool",
    name: "岩池猎手",
    art: "UNG_073",
    tier: 1,
    tribe: "murloc",
    atk: 2,
    hp: 3,
    keywords: [],
    effects: [{ kind: "battlecry_buff_tribe", tribe: "murloc", atk: 1, hp: 1 }],
    text: "战吼：使一个友方鱼人获得 +1/+1。",
  },
  {
    id: "annoyotron",
    name: "吵吵机器人",
    art: "GVG_085",
    tier: 1,
    tribe: "mech",
    atk: 1,
    hp: 2,
    keywords: ["taunt", "divineShield"],
    effects: [],
    text: "嘲讽。圣盾。",
  },
  {
    id: "micromachine",
    name: "微型机甲",
    art: "GVG_103",
    tier: 1,
    tribe: "mech",
    atk: 1,
    hp: 2,
    keywords: [],
    effects: [{ kind: "end_turn_buff_self", atk: 1, hp: 0 }],
    text: "在你的回合结束时，获得 +1 攻击力。",
  },
  {
    id: "scallywag",
    name: "海盗无赖",
    art: "BGS_061",
    tier: 1,
    tribe: "pirate",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [{ kind: "deathrattle_summon_attack", tokenId: "pirate_pal" }],
    text: "亡语：召唤一个 1/1 的海盗并使其立即发起攻击。",
  },
  {
    id: "wrathweaver",
    name: "愤怒编织者",
    art: "BGS_004",
    tier: 1,
    tribe: "neutral",
    atk: 1,
    hp: 3,
    keywords: [],
    effects: [{ kind: "on_play_tribe", tribe: "demon", atk: 2, hp: 1 }],
    text: "在你购买一个恶魔后，获得 +2/+1。",
  },
  {
    id: "selfless",
    name: "无私的英雄",
    art: "BGS_002",
    tier: 1,
    tribe: "neutral",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [{ kind: "deathrattle_give_shield" }],
    text: "亡语：使一个随机友方随从获得圣盾。",
  },
  {
    id: "tidecaller",
    name: "鱼人招潮者",
    art: "EX1_509",
    tier: 1,
    tribe: "murloc",
    atk: 1,
    hp: 2,
    keywords: [],
    effects: [{ kind: "on_summon_self_buff", tribe: "murloc", atk: 1, hp: 0 }],
    text: "每当你召唤一个鱼人，获得 +1 攻击力。",
  },
  {
    id: "micromummy",
    name: "微型木乃伊",
    art: "BOT_218",
    tier: 1,
    tribe: "mech",
    atk: 1,
    hp: 2,
    keywords: ["reborn"],
    effects: [{ kind: "end_turn_buff_random", atk: 1, hp: 0 }],
    text: "复生。在你的回合结束时，使一个随机友方随从获得 +1 攻击力。",
  },
  {
    id: "bloodsail",
    name: "血帆袭击者",
    art: "NEW1_018",
    tier: 1,
    tribe: "pirate",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [{ kind: "battlecry_buff_self_per_tribe", tribe: "pirate", atk: 1, hp: 0 }],
    text: "战吼：你每有一个其他海盗，便获得 +1 攻击力。",
  },

  // —— 2 级 ——
  {
    id: "spawn_nzoth",
    name: "恩佐斯的子嗣",
    art: "OG_256",
    tier: 2,
    tribe: "neutral",
    atk: 2,
    hp: 2,
    keywords: [],
    effects: [{ kind: "deathrattle_buff_all", atk: 1, hp: 1 }],
    text: "亡语：使你的所有随从获得 +1/+1。",
  },
  {
    id: "kaboombot",
    name: "爆破机器人",
    art: "BOT_606",
    tier: 2,
    tribe: "mech",
    atk: 2,
    hp: 2,
    keywords: [],
    effects: [{ kind: "deathrattle_damage_random", damage: 4 }],
    text: "亡语：对一个随机敌方随从造成 4 点伤害。",
  },
  {
    id: "harvestgolem",
    name: "麦田傀儡",
    art: "EX1_556",
    tier: 2,
    tribe: "mech",
    atk: 2,
    hp: 3,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "damaged_golem", count: 1 }],
    text: "亡语：召唤一个 2/1 的损坏的傀儡。",
  },
  {
    id: "unstableghoul",
    name: "蹒跚的食尸鬼",
    art: "FP1_024",
    tier: 2,
    tribe: "neutral",
    atk: 1,
    hp: 3,
    keywords: ["taunt"],
    effects: [{ kind: "deathrattle_damage_all", damage: 1 }],
    text: "嘲讽。亡语：对所有随从造成 1 点伤害。",
  },
  {
    id: "tidehunter",
    name: "鱼人猎潮者",
    art: "EX1_506",
    tier: 2,
    tribe: "murloc",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [{ kind: "battlecry_summon", tokenId: "murloc_scout" }],
    text: "战吼：召唤一个 1/1 的鱼人斥候。",
  },
  {
    id: "direwolf",
    name: "恐狼先锋",
    art: "EX1_162",
    tier: 2,
    tribe: "beast",
    atk: 2,
    hp: 2,
    keywords: [],
    effects: [{ kind: "start_combat_aura_adjacent", atk: 1 }],
    text: "相邻的随从获得 +1 攻击力。",
  },
  {
    id: "saurolisk",
    name: "狂暴的巨蜥",
    art: "BGS_020",
    tier: 2,
    tribe: "beast",
    atk: 3,
    hp: 2,
    keywords: [],
    effects: [{ kind: "on_play_deathrattle", atk: 1, hp: 2 }],
    text: "在你使用一张亡语随从后，获得 +1/+2。",
  },
  {
    id: "lepergnome",
    name: "麻风侏儒",
    art: "EX1_029",
    tier: 2,
    tribe: "neutral",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [{ kind: "deathrattle_damage_random", damage: 2 }],
    text: "亡语：对一个随机敌方随从造成 2 点伤害。",
  },
  {
    id: "sidekick",
    name: "欢快的同伴",
    art: "ULD_191",
    tier: 2,
    tribe: "neutral",
    atk: 1,
    hp: 2,
    keywords: [],
    effects: [{ kind: "battlecry_buff_random", atk: 0, hp: 2, taunt: true }],
    text: "战吼：使一个随机友方随从获得 +2 生命值和嘲讽。",
  },

  // —— 3 级 ——
  {
    id: "cavehydra",
    name: "洞穴多头蛇",
    art: "LOOT_078",
    tier: 3,
    tribe: "beast",
    atk: 2,
    hp: 4,
    keywords: ["cleave"],
    effects: [],
    text: "同时对攻击目标相邻的随从造成伤害。",
  },
  {
    id: "replicating",
    name: "量产型恐吓机",
    art: "BOT_312",
    tier: 3,
    tribe: "mech",
    atk: 3,
    hp: 1,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "microbot", count: 3 }],
    text: "亡语：召唤三个 1/1 的微型机器人。",
  },
  {
    id: "cobalt",
    name: "深蓝刃鳞龙人",
    art: "DRG_079",
    tier: 3,
    tribe: "dragon",
    atk: 5,
    hp: 5,
    keywords: [],
    effects: [{ kind: "end_turn_buff_random", atk: 3, hp: 0 }],
    text: "在你的回合结束时，使一个随机友方随从获得 +3 攻击力。",
  },
  {
    id: "southsea",
    name: "南海船长",
    art: "NEW1_027",
    tier: 3,
    tribe: "pirate",
    atk: 3,
    hp: 3,
    keywords: [],
    effects: [{ kind: "battlecry_buff_others", tribe: "pirate", atk: 1, hp: 1 }],
    text: "战吼：使你的其他海盗获得 +1/+1。",
  },
  {
    id: "grandmother",
    name: "慈祥的祖母",
    art: "KAR_005",
    tier: 3,
    tribe: "beast",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "bigbadwolf", count: 1 }],
    text: "亡语：召唤一只 3/2 的大灰狼。",
  },
  {
    id: "bronzewarden",
    name: "青铜守卫",
    art: "BGS_034",
    tier: 3,
    tribe: "dragon",
    atk: 2,
    hp: 1,
    keywords: ["divineShield", "reborn"],
    effects: [],
    text: "圣盾。复生。",
  },
  {
    id: "felfin",
    name: "邪鳍导航员",
    art: "BT_010",
    tier: 3,
    tribe: "murloc",
    atk: 4,
    hp: 4,
    keywords: [],
    effects: [{ kind: "battlecry_buff_others", tribe: "murloc", atk: 1, hp: 1 }],
    text: "战吼：使你的其他鱼人获得 +1/+1。",
  },
  {
    id: "screwjank",
    name: "废旧螺丝机",
    art: "GVG_055",
    tier: 3,
    tribe: "mech",
    atk: 2,
    hp: 5,
    keywords: [],
    effects: [{ kind: "battlecry_buff_tribe", tribe: "mech", atk: 2, hp: 2 }],
    text: "战吼：使一个友方机械获得 +2/+2。",
  },
  {
    id: "rascal",
    name: "喋喋不休的恶徒",
    art: "ICC_025",
    tier: 3,
    tribe: "neutral",
    atk: 2,
    hp: 2,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "nerubian", count: 1 }],
    text: "亡语：召唤一个 4/4 的蛛魔。",
  },

  // —— 4 级 ——
  {
    id: "mechanoegg",
    name: "机械蛋",
    art: "BOT_537",
    tier: 4,
    tribe: "mech",
    atk: 0,
    hp: 5,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "robosaur", count: 1 }],
    text: "亡语：召唤一个 8/8 的机械暴龙。",
  },
  {
    id: "highmane",
    name: "长鬃草原狮",
    art: "EX1_534",
    tier: 4,
    tribe: "beast",
    atk: 6,
    hp: 5,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "hyena", count: 2 }],
    text: "亡语：召唤两只 2/2 的土狼。",
  },
  {
    id: "argus",
    name: "阿古斯防御者",
    art: "EX1_093",
    tier: 4,
    tribe: "neutral",
    atk: 2,
    hp: 3,
    keywords: [],
    effects: [{ kind: "battlecry_buff_adjacent", atk: 1, hp: 1, taunt: true }],
    text: "战吼：使相邻的随从获得嘲讽和 +1/+1。",
  },
  {
    id: "foereaper",
    name: "死神 4000 型",
    art: "GVG_016",
    tier: 4,
    tribe: "mech",
    atk: 6,
    hp: 9,
    keywords: ["cleave"],
    effects: [],
    text: "同时对攻击目标相邻的随从造成伤害。",
  },
  {
    id: "infestedwolf",
    name: "寄生恶狼",
    art: "OG_216",
    tier: 4,
    tribe: "beast",
    atk: 3,
    hp: 3,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "spider", count: 2 }],
    text: "亡语：召唤两只 1/1 的蜘蛛。",
  },
  {
    id: "lightfang",
    name: "光牙执行者",
    art: "BGS_009",
    tier: 4,
    tribe: "neutral",
    atk: 2,
    hp: 2,
    keywords: [],
    effects: [{ kind: "end_turn_buff_each_tribe", atk: 2, hp: 2 }],
    text: "在你的回合结束时，使每种类型的一个友方随从获得 +2/+2。",
  },
  {
    id: "toxfin",
    name: "毒鳍鱼人",
    art: "DAL_077",
    tier: 4,
    tribe: "murloc",
    atk: 1,
    hp: 2,
    keywords: [],
    effects: [{ kind: "battlecry_give_poison", tribe: "murloc" }],
    text: "战吼：使一个友方鱼人获得剧毒。",
  },
  {
    id: "twilight",
    name: "暮光召唤者",
    art: "OG_272",
    tier: 4,
    tribe: "neutral",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [{ kind: "deathrattle_summon", tokenId: "twilight_5", count: 1 }],
    text: "亡语：召唤一个 5/5 的暮光元素。",
  },
  {
    id: "mechwarper",
    name: "机械跃迁者",
    art: "GVG_006",
    tier: 4,
    tribe: "mech",
    atk: 2,
    hp: 3,
    keywords: [],
    effects: [{ kind: "start_combat_aura_tribe", tribe: "mech", atk: 1, hp: 0 }],
    text: "你的其他机械获得 +1 攻击力。",
  },
  {
    id: "yeti",
    name: "机械雪人",
    art: "GVG_078",
    tier: 4,
    tribe: "mech",
    atk: 4,
    hp: 5,
    keywords: [],
    effects: [{ kind: "overkill_buff_self", atk: 2, hp: 2 }],
    text: "超杀：获得 +2/+2。",
  },

  // —— 5 级 ——
  {
    id: "voidlord",
    name: "虚空领主",
    art: "LOOT_368",
    tier: 5,
    tribe: "demon",
    atk: 3,
    hp: 9,
    keywords: ["taunt"],
    effects: [{ kind: "deathrattle_summon", tokenId: "voidwalker", count: 3 }],
    text: "嘲讽。亡语：召唤三个 1/3 并具有嘲讽的虚空行者。",
  },
  {
    id: "baron",
    name: "瑞文戴尔男爵",
    art: "FP1_031",
    tier: 5,
    tribe: "neutral",
    atk: 1,
    hp: 7,
    keywords: [],
    effects: [{ kind: "baron" }],
    text: "你的亡语会触发两次。",
  },
  {
    id: "brann",
    name: "布莱恩·铜须",
    art: "LOE_077",
    tier: 5,
    tribe: "neutral",
    atk: 2,
    hp: 4,
    keywords: [],
    effects: [{ kind: "brann" }],
    text: "你的战吼会触发两次。",
  },
  {
    id: "maexxna",
    name: "迈克斯纳",
    art: "FP1_010",
    tier: 5,
    tribe: "beast",
    atk: 2,
    hp: 8,
    keywords: ["poisonous"],
    effects: [],
    text: "剧毒。",
  },
  {
    id: "siegebreaker",
    name: "攻城恶魔",
    art: "EX1_185",
    tier: 5,
    tribe: "demon",
    atk: 6,
    hp: 8,
    keywords: ["taunt"],
    effects: [{ kind: "start_combat_aura_tribe", tribe: "demon", atk: 1, hp: 0 }],
    text: "嘲讽。你的其他恶魔获得 +1 攻击力。",
  },
  {
    id: "goldrinn",
    name: "戈德林",
    art: "BGS_018",
    tier: 5,
    tribe: "beast",
    atk: 4,
    hp: 4,
    keywords: [],
    effects: [{ kind: "deathrattle_buff_all", atk: 5, hp: 5, tribe: "beast" }],
    text: "亡语：使你的野兽获得 +5/+5。",
  },
  {
    id: "leeroy",
    name: "火车王里诺艾",
    art: "EX1_116",
    tier: 5,
    tribe: "neutral",
    atk: 6,
    hp: 2,
    keywords: [],
    effects: [{ kind: "start_combat_attack" }],
    text: "战斗开始时立即发起一次攻击。",
  },
  {
    id: "spiritwolf",
    name: "幽灵狼",
    art: "EX1_tk11",
    tier: 5,
    tribe: "beast",
    atk: 3,
    hp: 6,
    keywords: ["taunt"],
    effects: [{ kind: "avenge_buff_self", count: 3, atk: 3, hp: 2 }],
    text: "嘲讽。复仇（3）：获得 +3/+2。",
  },

  // —— 6 级 ——
  {
    id: "malganis",
    name: "玛尔加尼斯",
    art: "GVG_021",
    tier: 6,
    tribe: "demon",
    atk: 9,
    hp: 7,
    keywords: [],
    effects: [{ kind: "start_combat_aura_tribe", tribe: "demon", atk: 2, hp: 2 }],
    text: "你的其他恶魔获得 +2/+2。",
  },
  {
    id: "sneeds",
    name: "斯尼德的挖掘机",
    art: "GVG_114",
    tier: 6,
    tribe: "mech",
    atk: 5,
    hp: 7,
    keywords: [],
    effects: [{ kind: "deathrattle_summon_random_high" }],
    text: "亡语：召唤一个随机的高级随从。",
  },
  {
    id: "megasaur",
    name: "温顺的巨化兽",
    art: "UNG_089",
    tier: 6,
    tribe: "beast",
    atk: 5,
    hp: 4,
    keywords: [],
    effects: [{ kind: "battlecry_adapt_beasts", atk: 2, hp: 2 }],
    text: "战吼：使你的野兽获得 +2/+2 和圣盾。",
  },
  {
    id: "ragnaros",
    name: "拉格纳罗斯",
    art: "EX1_298",
    tier: 6,
    tribe: "neutral",
    atk: 8,
    hp: 8,
    keywords: [],
    effects: [{ kind: "start_combat_damage_random", damage: 8 }],
    text: "战斗开始时，对一个随机敌方随从造成 8 点伤害。",
  },
  {
    id: "illidan",
    name: "伊利丹·怒风",
    art: "EX1_614",
    tier: 6,
    tribe: "demon",
    atk: 7,
    hp: 5,
    keywords: [],
    effects: [{ kind: "on_friendly_summon_token", tokenId: "azzinoth" }],
    text: "在你召唤一个随从后，召唤一个 2/1 的埃辛诺斯之焰。",
  },
  {
    id: "mamabear",
    name: "熊妈妈",
    art: "BGS_021",
    tier: 6,
    tribe: "beast",
    atk: 4,
    hp: 4,
    keywords: [],
    effects: [{ kind: "on_summon_buff", tribe: "beast", atk: 5, hp: 5 }],
    text: "每当你召唤一个野兽，使其获得 +5/+5。",
  },
  {
    id: "nadina",
    name: "纳迪娜",
    art: "BGS_040",
    tier: 6,
    tribe: "dragon",
    atk: 7,
    hp: 4,
    keywords: [],
    effects: [{ kind: "deathrattle_divine_shield_tribe", tribe: "dragon" }],
    text: "亡语：使你的龙获得圣盾。",
  },
  {
    id: "impmama",
    name: "小鬼妈妈",
    art: "BGS_044",
    tier: 6,
    tribe: "demon",
    atk: 6,
    hp: 10,
    keywords: [],
    effects: [{ kind: "on_damaged_summon_random_demon" }],
    text: "每当本随从受到伤害，召唤一个随机恶魔。",
  },
  {
    id: "eliza",
    name: "艾丽莎提督",
    art: "BGS_081",
    tier: 6,
    tribe: "pirate",
    atk: 6,
    hp: 7,
    keywords: [],
    effects: [{ kind: "after_attack_buff_tribe", tribe: "pirate", atk: 1, hp: 1 }],
    text: "在一个友方海盗攻击后，使你的海盗获得 +1/+1。",
  },
  {
    id: "lichking",
    name: "巫妖王",
    art: "ICC_314",
    tier: 6,
    tribe: "neutral",
    atk: 8,
    hp: 8,
    keywords: ["taunt"],
    effects: [{ kind: "end_turn_buff_rightmost", atk: 2, hp: 2 }],
    text: "嘲讽。在你的回合结束时，使你最右边的随从获得 +2/+2。",
  },
  {
    id: "jaraxxus",
    name: "加拉克苏斯大王",
    art: "EX1_323",
    tier: 6,
    tribe: "demon",
    atk: 3,
    hp: 15,
    keywords: [],
    effects: [{ kind: "end_turn_summon", tokenId: "imp" }],
    text: "在你的回合结束时，召唤一个 1/1 的小鬼。",
  },

  // —— 衍生物 ——
  {
    id: "tabbycat",
    name: "虎斑猫",
    art: "CFM_315t",
    tier: 1,
    tribe: "beast",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "pirate_pal",
    name: "海盗水手",
    art: "CS2_146",
    tier: 1,
    tribe: "pirate",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "damaged_golem",
    name: "损坏的傀儡",
    art: "skele21",
    tier: 1,
    tribe: "mech",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "murloc_scout",
    name: "鱼人斥候",
    art: "EX1_506a",
    tier: 1,
    tribe: "murloc",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "microbot",
    name: "微型机器人",
    art: "BOT_312t",
    tier: 1,
    tribe: "mech",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "bigbadwolf",
    name: "大灰狼",
    art: "KAR_005a",
    tier: 1,
    tribe: "beast",
    atk: 3,
    hp: 2,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "robosaur",
    name: "机械暴龙",
    art: "BOT_537t",
    tier: 1,
    tribe: "mech",
    atk: 8,
    hp: 8,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "hyena",
    name: "土狼",
    art: "EX1_534t",
    tier: 1,
    tribe: "beast",
    atk: 2,
    hp: 2,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "spider",
    name: "幽灵蜘蛛",
    art: "FP1_002t",
    tier: 1,
    tribe: "beast",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "voidwalker",
    name: "虚空行者",
    art: "CS2_065",
    tier: 1,
    tribe: "demon",
    atk: 1,
    hp: 3,
    keywords: ["taunt"],
    effects: [],
    text: "嘲讽。",
    token: true,
  },
  {
    id: "azzinoth",
    name: "埃辛诺斯之焰",
    art: "EX1_614t",
    tier: 1,
    tribe: "demon",
    atk: 2,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "nerubian",
    name: "蛛魔",
    art: "FP1_007t",
    tier: 1,
    tribe: "neutral",
    atk: 4,
    hp: 4,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "twilight_5",
    name: "暮光元素",
    art: "ICC_019t",
    tier: 1,
    tribe: "neutral",
    atk: 5,
    hp: 5,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
  {
    id: "imp",
    name: "小鬼",
    art: "BRM_006t",
    tier: 1,
    tribe: "demon",
    atk: 1,
    hp: 1,
    keywords: [],
    effects: [],
    text: "",
    token: true,
  },
];

export const MINION_BY_ID: Record<string, MinionDef> = Object.fromEntries(
  MINIONS.map((m) => [m.id, m]),
);

export const COLLECTIBLE = MINIONS.filter((m) => !m.token);

export const BY_TIER: Record<number, MinionDef[]> = {
  1: COLLECTIBLE.filter((m) => m.tier === 1),
  2: COLLECTIBLE.filter((m) => m.tier === 2),
  3: COLLECTIBLE.filter((m) => m.tier === 3),
  4: COLLECTIBLE.filter((m) => m.tier === 4),
  5: COLLECTIBLE.filter((m) => m.tier === 5),
  6: COLLECTIBLE.filter((m) => m.tier === 6),
};

export const COPIES_PER_TIER = [0, 16, 15, 13, 11, 9, 7];
export const SHOP_SIZE = [0, 3, 4, 4, 5, 5, 6];
export const UPGRADE_BASE = [0, 5, 7, 8, 9, 10];
export const MAX_BOARD = 7;
export const MAX_HAND = 10;
export const BUY_COST = 3;
export const REFRESH_COST = 1;
export const SELL_REWARD = 1;
export const START_HP = 30;
export const MAX_GOLD = 10;

export function defOf(id: string): MinionDef {
  const d = MINION_BY_ID[id];
  if (!d) throw new Error(`Unknown minion ${id}`);
  return d;
}

export function makeInst(defId: string, golden = false): MinionInst {
  const d = defOf(defId);
  const atk = golden ? d.atk * 2 : d.atk;
  const hp = golden ? d.hp * 2 : d.hp;
  return {
    uid: uid("m"),
    defId,
    atk,
    hp,
    maxHp: hp,
    golden,
    keywords: [...d.keywords],
  };
}

export function scaleN(n: number, golden: boolean): number {
  return golden ? n * 2 : n;
}

export function artUrl(art: string): string {
  return `/art/${art}.jpg`;
}

export function minionValue(m: MinionInst): number {
  const d = defOf(m.defId);
  let v = d.tier * 10 + m.atk * 2 + m.hp;
  if (m.keywords.includes("taunt")) v += 3;
  if (m.keywords.includes("divineShield")) v += 5;
  if (m.keywords.includes("poisonous")) v += 8;
  if (m.keywords.includes("reborn")) v += 6;
  if (m.keywords.includes("cleave")) v += 6;
  if (m.golden) v += 18;
  if (d.effects.length) v += d.effects.length * 4;
  return v;
}
